name = "swse-backend"
main = "main.py"
compatibility_date = "2024-04-01"
compatibility_flags = ["python_workers"]

[vars]
GOOGLE_CLIENT_ID = "mock_google_id"
SESSION_SECRET = "mock_session_secret"

[[d1_databases]]
binding = "DB"
database_name = "swse-db"
database_id = "local-db-id"
