name = "swse-backend"
main = "main.py"
compatibility_date = "2024-04-01"
compatibility_flags = ["python_workers"]

[dev]
ip = "0.0.0.0"
port = 8787

[vars]
GOOGLE_CLIENT_ID = "mock_google_id"
SESSION_SECRET = "mock_session_secret"

[[d1_databases]]
binding = "DB"
database_name = "swse-db"
database_id = "550e8400-e29b-41d4-a716-446655440000"
